acclimate_regions = [
    'AFG', 'ALB', 'DZA', 'AND', 'AGO', 'ATG', 'ARG', 'ARM', 'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB',
    'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BIH', 'BWA', 'BRA', 'VGB', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM',
    'CMR', 'CAN', 'CPV', 'CYM', 'CAF', 'TCD', 'CHL', 'CN.AH', 'CN.BJ', 'CN.CQ', 'CN.FJ', 'CN.GS', 'CN.GD', 'CN.GX',
    'CN.GZ', 'CN.HA', 'CN.HB', 'CN.HL', 'CN.HE', 'CN.HU', 'CN.HN', 'CN.JS', 'CN.JX', 'CN.JL', 'CN.LN', 'CN.NM', 'CN.NX',
    'CN.QH', 'CN.SA', 'CN.SD', 'CN.SH', 'CN.SX', 'CN.SC', 'CN.TJ', 'CN.XJ', 'CN.XZ', 'CN.YN', 'CN.ZJ', 'COL', 'COG',
    'CRI', 'HRV', 'CUB', 'CYP', 'CZE', 'CIV', 'PRK', 'COD', 'DNK', 'DJI', 'DOM', 'ECU', 'EGY', 'SLV', 'ERI', 'EST',
    'ETH', 'FJI', 'FIN', 'FRA', 'PYF', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GRC', 'GRL', 'GTM', 'GIN', 'GUY', 'HTI',
    'HND', 'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR', 'ITA', 'JAM', 'JPN', 'JOR', 'KAZ', 'KEN',
    'KWT', 'KGZ', 'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU', 'LUX', 'MAC', 'MDG', 'MWI', 'MYS', 'MDV',
    'MLI', 'MLT', 'MRT', 'MUS', 'MEX', 'MCO', 'MNG', 'MNE', 'MAR', 'MOZ', 'MMR', 'NAM', 'NPL', 'NLD', 'ANT', 'NCL',
    'NZL', 'NIC', 'NER', 'NGA', 'NOR', 'PSE', 'OMN', 'PAK', 'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'POL', 'PRT', 'QAT',
    'KOR', 'MDA', 'ROU', 'RUS', 'RWA', 'WSM', 'SMR', 'STP', 'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP', 'SVK', 'SVN',
    'SOM', 'ZAF', 'SSD', 'ESP', 'LKA', 'SDN', 'SUR', 'SWZ', 'SWE', 'CHE', 'SYR', 'TWN', 'TJK', 'THA', 'MKD', 'TGO',
    'TTO', 'TUN', 'TUR', 'TKM', 'UGA', 'UKR', 'ARE', 'GBR', 'TZA', 'US.AL', 'US.AK', 'US.AZ', 'US.AR', 'US.CA', 'US.CO',
    'US.CT', 'US.DE', 'US.DC', 'US.FL', 'US.GA', 'US.HI', 'US.ID', 'US.IL', 'US.IN', 'US.IA', 'US.KS', 'US.KY', 'US.LA',
    'US.ME', 'US.MD', 'US.MA', 'US.MI', 'US.MN', 'US.MS', 'US.MO', 'US.MT', 'US.NE', 'US.NV', 'US.NH', 'US.NJ', 'US.NM',
    'US.NY', 'US.NC', 'US.ND', 'US.OH', 'US.OK', 'US.OR', 'US.PA', 'US.RI', 'US.SC', 'US.SD', 'US.TN', 'US.TX', 'US.UT',
    'US.VT', 'US.VA', 'US.WA', 'US.WV', 'US.WI', 'US.WY', 'URY', 'UZB', 'VUT', 'VEN', 'VNM', 'YEM', 'ZMB', 'ZWE']
